## Switches
set_property PACKAGE_PIN V17 [get_ports {I_Switch[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {I_Switch[0]}]
set_property PACKAGE_PIN V16 [get_ports {I_Switch[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {I_Switch[1]}]
set_property PACKAGE_PIN W16 [get_ports {I_Switch[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {I_Switch[2]}]
set_property PACKAGE_PIN W17 [get_ports {I_Switch[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {I_Switch[3]}]
set_property PACKAGE_PIN W15 [get_ports {I_Switch[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {I_Switch[4]}]
set_property PACKAGE_PIN V15 [get_ports {I_Switch[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {I_Switch[5]}]
set_property PACKAGE_PIN W14 [get_ports {I_Switch[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {I_Switch[6]}]
set_property PACKAGE_PIN W13 [get_ports {I_Switch[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {I_Switch[7]}]
set_property PACKAGE_PIN V2 [get_ports {I_Switch[8]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {I_Switch[8]}]
set_property PACKAGE_PIN T3 [get_ports {I_Switch[9]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {I_Switch[9]}]
set_property PACKAGE_PIN T2 [get_ports {I_Switch[10]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {I_Switch[10]}]
set_property PACKAGE_PIN R3 [get_ports {I_Switch[11]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {I_Switch[11]}]
set_property PACKAGE_PIN W2 [get_ports {I_Switch[12]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {I_Switch[12]}]
set_property PACKAGE_PIN U1 [get_ports {I_Switch[13]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {I_Switch[13]}]
set_property PACKAGE_PIN T1 [get_ports {I_Switch[14]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {I_Switch[14]}]
set_property PACKAGE_PIN R2 [get_ports {I_Switch[15]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {I_Switch[15]}]



## Lights
set_property PACKAGE_PIN U16 [get_ports {O_Led[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Led[0]}]
set_property PACKAGE_PIN E19 [get_ports {O_Led[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Led[1]}]
set_property PACKAGE_PIN U19 [get_ports {O_Led[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Led[2]}]
set_property PACKAGE_PIN V19 [get_ports {O_Led[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Led[3]}]
set_property PACKAGE_PIN W18 [get_ports {O_Led[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Led[4]}]
set_property PACKAGE_PIN U15 [get_ports {O_Led[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Led[5]}]
set_property PACKAGE_PIN U14 [get_ports {O_Led[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Led[6]}]
set_property PACKAGE_PIN V14 [get_ports {O_Led[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Led[7]}]
set_property PACKAGE_PIN V13 [get_ports {O_Led[8]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Led[8]}]
set_property PACKAGE_PIN V3 [get_ports {O_Led[9]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Led[9]}]
set_property PACKAGE_PIN W3 [get_ports {O_Led[10]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Led[10]}]
set_property PACKAGE_PIN U3 [get_ports {O_Led[11]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Led[11]}]
set_property PACKAGE_PIN P3 [get_ports {O_Led[12]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Led[12]}]
set_property PACKAGE_PIN N3 [get_ports {O_Led[13]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Led[13]}]
set_property PACKAGE_PIN P1 [get_ports {O_Led[14]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Led[14]}]
set_property PACKAGE_PIN L1 [get_ports {O_Led[15]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Led[15]}]


##7 segment display
set_property PACKAGE_PIN W7 [get_ports {O_Segment[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Segment[0]}]
set_property PACKAGE_PIN W6 [get_ports {O_Segment[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Segment[1]}]
set_property PACKAGE_PIN U8 [get_ports {O_Segment[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Segment[2]}]
set_property PACKAGE_PIN V8 [get_ports {O_Segment[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Segment[3]}]
set_property PACKAGE_PIN U5 [get_ports {O_Segment[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Segment[4]}]
set_property PACKAGE_PIN V5 [get_ports {O_Segment[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Segment[5]}]
set_property PACKAGE_PIN U7 [get_ports {O_Segment[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Segment[6]}]

#set_property PACKAGE_PIN V7 [get_ports dp]
	#set_property IOSTANDARD LVCMOS33 [get_ports dp]

set_property PACKAGE_PIN W5 [get_ports Dom_Main_Dom_Clk]
	set_property IOSTANDARD LVCMOS33 [get_ports Dom_Main_Dom_Clk]

set_property PACKAGE_PIN U2 [get_ports {O_Anode[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Anode[0]}]
set_property PACKAGE_PIN U4 [get_ports {O_Anode[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Anode[1]}]
set_property PACKAGE_PIN V4 [get_ports {O_Anode[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Anode[2]}]
set_property PACKAGE_PIN W4 [get_ports {O_Anode[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {O_Anode[3]}]


##Buttons
#set_property PACKAGE_PIN U18 [get_ports BTNC]
#	set_property IOSTANDARD LVCMOS33 [get_ports BTNC]
#set_property PACKAGE_PIN T18 [get_ports BTNU]
#	set_property IOSTANDARD LVCMOS33 [get_ports BTNU]
set_property PACKAGE_PIN W19 [get_ports BTNL]
	set_property IOSTANDARD LVCMOS33 [get_ports BTNL]
set_property PACKAGE_PIN T17 [get_ports BTNR]
	set_property IOSTANDARD LVCMOS33 [get_ports BTNR]
#set_property PACKAGE_PIN U17 [get_ports BTND]
#	set_property IOSTANDARD LVCMOS33 [get_ports BTND]


## Configuration options, can be used for all designs
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
